#!/bin/bash
# Fill in original sources in the results from a FindClones run

ulimit -s hard

# Find our installation
lib="${0%%/scripts/GetSource}"
if [ ! -d ${lib} ]
then
    echo "*** Error:  cannot find NiCad installation ${lib}"
    echo ""
    exit 99
fi

date

for clonesfile in $*
do
    # Check we have a system
    if [ ! -f "$clonesfile" ] 
    then
	echo "Usage:  GetSource system-name_granularity-clones/system-name_granularity-clones-threshold.xml"
	echo "  (Output in system-name_granularity-clones/system-name_granularity-clones-threshold-withsource.xml)"
	echo "  e.g., GetSource systems/c/linux_functions-clones/linux_functions-clones-0.2.xml"
	exit 99
    fi

    # Get path of clone results file
    basename=${clonesfile%%.xml}

    # OK, let's run it
    echo "${lib}/tools/getsource.x ${basename}.xml ${basename}-withsource.xml"
    time ${lib}/tools/getsource.x ${basename}.xml ${basename}-withsource.xml
    result=$?

    if [ ${result} != 0 ]
    then
	exit $result
    fi
done

echo ""
date
echo ""

exit 0
